name: SpidrApp
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.0+33

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_cropper: ^1.2.1
  flutter_web_browser: "^0.14.0"
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  google_fonts: ^1.1.2
  firebase_auth: ^0.18.1+2
  cloud_firestore: ^0.14.1+3
  shared_preferences: ^0.5.12+4
  firebase_core : ^0.5.3
  firebase_storage: ^5.0.1
  intl: ^0.16.1
  dynamic_text_highlighting: ^2.2.0
  camera: ^0.7.0+2
  image_picker: ^0.6.7+22
  path: ^1.8.0
  path_provider: ^1.6.24
  esys_flutter_share: ^1.0.2
  firebase_messaging: ^7.0.3
  google_sign_in: ^4.5.9
  fluttertoast: ^8.0.7
  flutter_staggered_grid_view: ^0.3.4
  flutter_launcher_icons: ^0.8.1
  file_picker: ^2.1.6
  filesize: ^2.0.1
  flutter_downloader: ^1.6.1
  fluttericon: ^2.0.0
  flutter_markdown: ^0.5.2
  flutter_image_compress: ^1.0.0
  firebase_analytics: ^6.3.0
  font_awesome_flutter: ^9.1.0
  cached_network_image: ^2.5.1
  mime: ^1.0.0
  flutter_icons: ^1.1.0
  carousel_slider: ^4.0.0
  photo_manager: ^1.2.5

  photo_view: ^0.11.1
  scrollable_positioned_list: ^0.1.10
  flash: ^1.5.1
  pull_to_refresh: ^2.0.0
  apple_sign_in: ^0.1.0
  provider: ^4.3.3
  flutter_linkify: ^5.0.2
  linkify: ^4.0.0
  introduction_screen: ^2.1.0
  any_link_preview: ^1.0.8
  video_thumbnail: ^0.3.3
  advance_pdf_viewer: ^1.2.2
  simple_url_preview: ^2.0.0

  giphy_get: ^1.1.2+1
  algolia: ^0.1.7

  video_player: ^2.1.10
  video_compress: ^3.1.0

  flare_flutter: ^3.0.1
  rive: ^0.7.12

  permission_handler: ^5.1.0+2




dev_dependencies:
  flutter_test:
    sdk: flutter



flutter_icons:
  image_path: 'assets/icon/SpidrIcon.png'
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/animations/
    - assets/audios/
    - assets/images/
    - assets/icon/
    - assets/icon/bottomNavBar/
    - assets/images/groupPic/
    - assets/images/userPic/
    - assets/imagesp/images/
    - ios/Podfile.lock



      #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
      #    - family: WorkSansSemiBold
      #      fonts:
      #        - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf
      #
      #    - family: WorkSansBold
      #      fonts:
      #        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf
      #
      #    - family: WorkSansMedium
    #      fonts:
    #        - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
